# Netlify Configuration for Burley's Website

[build]
  # Publish directory (root directory in this case)
  publish = "."
  
  # Functions directory
  functions = "netlify/functions"

[functions]
  # Set Node.js version
  node_bundler = "esbuild"

# Redirect rules (if needed)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

